[mypy]
files = .
plugins = mypy_django_plugin.main
mypy_path = stubs
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
strict_equality = True
exclude = venv|virtualenv

[mypy.plugins.django-stubs]
django_settings_module = udac.settings

[mypy.file_bucket.*]
disallow_any_generics = True
disallow_subclassing_any = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_return_any = True
no_implicit_reexport = True

# These libraries have no typehints, maybe we can write stubs for them
# later.
[mypy-bs4.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-flanker.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-pymdownx.*]
ignore_missing_imports = True

[mypy-selenium.*]
ignore_missing_imports = True

[mypy-pytest_django.*]
ignore_missing_imports = True

[mypy-faker.*]
ignore_missing_imports = True

[mypy-requests_mock.*]
ignore_missing_imports = True

[mypy-glom.*]
ignore_missing_imports = True

[mypy-paramiko.*]
ignore_missing_imports = True

[mypy-humanize.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-isoweek.*]
ignore_missing_imports = True

[mypy-semver.*]
ignore_missing_imports = True

[mypy-seleniumlogin.*]
ignore_missing_imports = True

[mypy-urllib3.*]
ignore_missing_imports = True

[mypy-htmlmin.*]
ignore_missing_imports = True

[mypy-messagebird]
ignore_missing_imports = True

[mypy-django_weasyprint.*]
ignore_missing_imports = True

[mypy-google.cloud.*]
ignore_missing_imports = True

[mypy-django_summernote.*]
ignore_missing_imports = True
