# Generated by Django 3.0.7 on 2021-11-08 18:05
from typing import Any, List

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.CharField(max_length=512, verbose_name="Question")),
                ("answer", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField()),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=64, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "house_flat_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="House / Flat Number",
                    ),
                ),
                ("city", models.CharField(max_length=64, verbose_name="Town / City")),
                ("postcode", models.CharField(max_length=10, verbose_name="Post Code")),
                (
                    "registration",
                    models.CharField(max_length=10, verbose_name="Reg Number"),
                ),
                ("car", models.CharField(max_length=256, verbose_name="Car")),
                ("engine", models.CharField(max_length=256, verbose_name="Engine")),
                ("color", models.CharField(max_length=64, verbose_name="Color")),
                ("has_v5", models.BooleanField(default=True, verbose_name="Has V5")),
                (
                    "wheels_on",
                    models.BooleanField(default=True, verbose_name="Wheels On"),
                ),
                (
                    "drop_off",
                    models.BooleanField(default=False, verbose_name="Drop Off"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=512, verbose_name="Title")),
                ("content", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("content", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicle_images/")),
                ("primary", models.BooleanField(default=False, verbose_name="Primary")),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="www.Lead",
                    ),
                ),
            ],
        ),
    ]
