# Generated by Django 3.0.7 on 2021-11-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="sent_at",
            field=models.DateTimeField(null=True),
        ),
    ]
