# Generated by Django 3.0.7 on 2021-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0002_sent_at_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="nice_location",
            field=models.CharField(
                default="bruh", max_length=512, verbose_name="Nice Location"
            ),
            preserve_default=False,
        ),
    ]
