# Generated by Django 3.0.7 on 2021-11-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0003_add_nice_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Phone"
            ),
        ),
    ]
