# Generated by Django 3.0.7 on 2022-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0004_add_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barometer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
