# Generated by Django 3.0.7 on 2022-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0005_barometer"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="news-images/"),
        ),
    ]
