# Generated by Django 3.0.7 on 2022-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0006_news_featureds"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(
                default="News", max_length=32, verbose_name="Category"
            ),
        ),
    ]
