# Generated by Django 3.0.7 on 2022-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0007_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="pre_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
