# Generated by Django 3.0.7 on 2022-07-15 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0008_news_pre_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="news",
            name="created_at",
        ),
        migrations.AddField(
            model_name="faq",
            name="Creation Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="news",
            name="Creation Date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
