# Generated by Django 3.0.7 on 2022-07-15 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0009_editable_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="Creation Date",
        ),
        migrations.RemoveField(
            model_name="news",
            name="Creation Date",
        ),
        migrations.AddField(
            model_name="faq",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation Date"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation Date"
            ),
        ),
    ]
