# Generated by Django 3.0.7 on 2022-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0010_editable_dates_verbose"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="youtube_url",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="YouTube Link"
            ),
        ),
    ]
