# Generated by Django 3.0.7 on 2022-09-02 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0011_review_youtube"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation Date"
                    ),
                ),
                ("slug", models.CharField(max_length=64, verbose_name="Slug")),
                (
                    "heading",
                    models.CharField(max_length=256, verbose_name="Page Heading"),
                ),
                ("subheading", models.TextField(blank=True, null=True)),
                ("quote", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("news_items", models.ManyToManyField(to="www.News")),
                ("testimonial_items", models.ManyToManyField(to="www.Review")),
            ],
        ),
    ]
